### ISSUE TITLE
is there have an android project for test/?

### ISSUE THREAD

**Issue by jaccen** [lethiandev/godot-cpp-cmake#1]
is there have a android project for test/?

**Comment by lethiandev** [comment]
Hello, I'm developing those CMake scripts mainly for my own projects so there is no examples at all, but as an example for Android build, you can check one of my Godot's project also located on github: https://github.com/lethiandev/battle-tanks/tree/master/native

**Comment by jaccen** [comment]
this project ,i found not an Android project,
how can  modify on android ? only add the source and lib in an Android project ?

**Comment by lethiandev** [comment]
Actually, BattleTanks is a cross-platform project, that works on Windows, Linux, Android and Emscripten (HTML5) too. Sorry, but i don't have any clean, simple and Android's platform only oriented example. But you can copy-paste some files from the project and modify them as for your needs.
